name: Frontend CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2


      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Test AWS Credentials and S3 Bucket Access
      - name: Verify AWS Credentials and S3 Bucket Access
        run: |
          echo "Testing AWS credentials and S3 access..."
          aws s3 ls s3://${{ secrets.S3_BUCKET }} --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Step 4: Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 5: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # Step 6: Build the frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # Step 7: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: frontend/build/


      # Step 8: Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/build s3://${{ secrets.S3_BUCKET }}/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
