name: Frontend CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
      
      # Step 2: Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # Step 3: Install dependencies
      - run: npm install
      
      # Step 4: Run Jest tests
      - name: Run Jest tests
        run: npm test
        env:
          CI: true
      
      # Step 5: Build the frontend
      - run: npm run build
      
      # Step 6: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

      # Step 6: Upload build artifacts to aws s3
      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/build s3://S3_BUCKET/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}