name: Frontend CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
      
      # Step 2: Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # Step 3: Navigate to frontend directory
      - name: Change directory to frontend
        run: cd frontend
      
      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  # Ensure npm runs inside the frontend directory
      
      # Step 5: Build the frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend  # Ensure the build happens in the frontend directory
      
      # Step 6: Install AWS CLI (ensure AWS CLI is installed in the runner)
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Step 7: Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/build s3://$S3_BUCKET/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
