name: Frontend CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  # Calling the reusable `run_tests.yml` workflow
  tests:
    uses: ./.github/workflows/run_tests.yml  # Path to reusable workflow
    secrets:  # Pass the required secrets to the reusable workflow
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Define other jobs like build and deploy
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      
      # Build frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1  # Ensure correct version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Sync the build to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/build s3://${{ secrets.S3_BUCKET }}/ --delete
