name: Frontend CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      S3_BUCKET: ${{ secrets.S3_BUCKET }}  # Corrected this line
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
      
      # Step 2: Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      
      # Step 4: Build the frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
      
      # Step 5: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: frontend/build/
      
      # Step 6: Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/build s3://$S3_BUCKET/ --delete
