name: Frontend CI Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # Step 4: Build the frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
      
      # Step 5: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: frontend/build/
      
      # Step 6: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::202533534284:role/awsGitHubActionsRole
        
          aws-region: us-east-1
   

      # Step 7: Deploy to S3-test
      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/build s3://${{ secrets.S3_BUCKET }}/ --delete
